name: Push to GCR GitHub Action

on:
  push:
    tags:
      - v*

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - uses: actions/checkout@v2

      - name: Login to google
        run: |
          echo ${{ secrets.GCLOUD_SERVICE_KEY }} | python -m base64 -d >/tmp/key.json 2>/dev/null
          cat /tmp/key.json | docker login -u _json_key --password-stdin https://us.gcr.io

      - name: Build
        run: |
          docker build -t us.gcr.io/mcdex3/mai3data-api:${{ steps.get_version.outputs.VERSION }} .
          docker push us.gcr.io/mcdex3/mai3data-api:${{ steps.get_version.outputs.VERSION }}
